### ISSUE TITLE
Discord integration API

### ISSUE THREAD

**Issue by BasSarrechia** [BasSarrechia/rpg-bot#1]
What discord API do we want to use?

**Comment by BasSarrechia** [comment]
https://github.com/DV8FromTheWorld/JDA
JDA
advantages: seems wide userd, Atrum uses it too (referenceable)

**Comment by BasSarrechia** [comment]
https://discord4j.com/

**Comment by BasSarrechia** [comment]
https://github.com/mewna/catnip

**Comment by BasSarrechia** [comment]
https://github.com/Javacord/Javacord

**Comment by saramaebee** [comment]
Javacord decided.
